/**
 * CI check: validates the sitemap has no duplicate URLs.
 * Collects routes from the same sources as app/sitemap.ts and flags any duplication.
 *
 * Usage: npx tsx scripts/check-sitemap.ts
 */

import fs from "fs";
import path from "path";
import {
  getAllServiceSlugsFromContent,
  getAllIndustrySlugsFromContent,
  getAllUseCaseSlugsFromContent,
  getAllSlugs,
} from "../lib/content";

const BASE_URL = "https://procedure.tech";

/**
 * Same logic as app/sitemap.ts discoverStaticAppRoutes()
 */
function discoverStaticAppRoutes(): string[] {
  const appDir = path.join(process.cwd(), "app");
  const routes: string[] = [];

  function scanDir(dir: string, prefix: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const hasPage = entries.some((e) => e.isFile() && e.name === "page.tsx");
    if (hasPage) {
      routes.push(prefix || "/");
    }
    for (const entry of entries) {
      if (
        entry.isDirectory() &&
        !entry.name.startsWith("[") &&
        !entry.name.startsWith("_") &&
        !entry.name.startsWith("(")
      ) {
        scanDir(path.join(dir, entry.name), `${prefix}/${entry.name}`);
      }
    }
  }

  scanDir(appDir, "");
  return routes;
}

function main() {
  const allUrls: { url: string; source: string }[] = [];

  // Static app routes
  for (const route of discoverStaticAppRoutes()) {
    allUrls.push({ url: `${BASE_URL}${route}`, source: "app/ directory" });
  }

  // Dynamic content routes
  for (const slug of getAllServiceSlugsFromContent()) {
    allUrls.push({
      url: `${BASE_URL}/services/${slug}`,
      source: "content/services/",
    });
  }
  for (const slug of getAllIndustrySlugsFromContent()) {
    allUrls.push({
      url: `${BASE_URL}/industries/${slug}`,
      source: "content/industries/",
    });
  }
  for (const slug of getAllUseCaseSlugsFromContent()) {
    allUrls.push({
      url: `${BASE_URL}/use-cases/${slug}`,
      source: "content/use-cases/",
    });
  }
  for (const slug of getAllSlugs("blog")) {
    allUrls.push({
      url: `${BASE_URL}/blogs/${slug}`,
      source: "content/blog/",
    });
  }

  // Check for duplicates
  const seen = new Map<string, string[]>();
  for (const { url, source } of allUrls) {
    const sources = seen.get(url) || [];
    sources.push(source);
    seen.set(url, sources);
  }

  const duplicates = [...seen.entries()].filter(([, sources]) => sources.length > 1);

  if (duplicates.length > 0) {
    console.error(`\n❌ Found ${duplicates.length} duplicate sitemap URL(s):\n`);
    for (const [url, sources] of duplicates) {
      console.error(`  ${url}`);
      console.error(`    Sources: ${sources.join(", ")}\n`);
    }
    console.error(
      "Fix: ensure each URL is generated by only one source in app/sitemap.ts\n"
    );
    process.exit(1);
  }

  const unique = seen.size;
  console.log(`✓ Sitemap OK: ${unique} unique URLs, no duplicates`);
}

main();
